ActionBar:
    #size: (100, 100)
    size_hint: (0.5, 0.5)
    pos_hint: {'top':1}
    ActionView:
        use_separator: True
        ActionPrevious:
            title: 'M083140005'
            with_previous: False
        ActionButton:
            important: True
            text: 'READ'
        ActionButton:
            text: 'RESET'
        ActionButton:
            text: 'RUN'
        ActionButton:
            text: 'OUTPUT'
        ActionButton:
            text: 'QUIT'